bot:
  name: name
  token: token
url:
  firstPart: firstPart
  sheetId: sheetId
  apiKey: apiKey
baseIdList: baseIdList
settingsList: settingsList
adminChatId: adminChatId
studentsList: Absenteeism
correspondenceOfDates: correspondenceOfDates

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
        ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
