bot:
  name: name
  token: token
url:
  firstPart: firstPart
  sheetId: sheetId
  apiKey: apiKey

application:
  fields-name:
    laboratoryNotebookColumn: C
    testNotebookColumn: D
    startMarksColumn: K
    endMarksColumn: BZ
    startQuarterMarksColumn: E
    endQuarterMarksColumn: J
    dateField: 2
    fieldTypeOfWork: 3
  sheet-lists:
    baseIdList: baseIdList
    settingsList: settingsList
    studentsList: Absenteeism
adminChatId: adminChatId

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
        ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
