bot:
  name: lyceumteacher_bot
  token: 123
url:
  firstPart: https://sheets.googleapis.com/v4/spreadsheets/
  sheetId: 123
  apiKey: 123
filePath: baseId.csv
spring:
  main:
    web-application-type: none